language: node_js
node_js:
  - "12"

sudo: required
services:
  - docker

# S3 Policy required:
# {
#   "Version": "2012-10-17",
#   "Statement": [
#       {
#           "Sid": "VisualEditor0",
#           "Effect": "Allow",
#           "Action": [
#               "s3:PutObject",
#               "s3:GetObject",
#               "s3:ListBucket",
#               "s3:DeleteObject",
#               "s3:GetBucketLocation",
#               "s3:s3:PutObjectAcl"
#           ],
#           "Resource": [
#               "arn:aws:s3:::fe-intro-courseware",
#               "arn:aws:s3:::fe-intro-courseware/*"
#           ]
#       },
#       {
#           "Sid": "VisualEditor1",
#           "Effect": "Allow",
#           "Action": "s3:HeadBucket",
#           "Resource": "*"
#       }
#   ]
# }

script:
  - npm install
  - npm install gitbook-cli surge -g
  - gitbook install
  - gitbook build
  - surge --domain http://fe-intro-courseware.surge.sh/ --project ./_book
  - docker run --env AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --env AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -v `pwd`:/src amazon/aws-cli s3 sync /src/_book s3://${s3bucket}/ --delete --acl public-read

