language: node_js
node_js:
  - "12"

sudo: required
services:
  - docker

script:
  - npm install
  - npm install gitbook-cli surge -g
  - gitbook install
  - gitbook build
  - surge --domain http://fe-intro-courseware.surge.sh/ --project ./_book
  - docker run --env AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --env AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} amazon/aws-cli s3 sync ./_book s3://${s3bucket}/ . --delete